---
- hosts: all
  become: true
  tasks:
        - name: Instalacion Escritorio
          apt: name={{ item }} state=installed
          with_items:
                  #- lubuntu-desktop
                  - ubuntu-mate-desktop      
        - name: Instalacion de LDAP cliente
          apt: name={{ item }} state=installed
          with_items:
                  - libnss-ldap
                  - libpam-ldap
        
        - name: Configuracion nsswitch LDAP
          copy: src=template/nss_cliente dest=/etc/nsswitch.conf
        
        - name: Configuracion common-session LDAP
          copy: src=template/common-session dest=/etc/pam.d/common-session
       
        - name: Configuracion common-password LDAP
          copy: src=template/common-password dest=/etc/pam.d/common-password

        - name: Configuracion ldap.conf LDAP
          copy: src=template/ldap.conf dest=/etc/ldap.conf

        - name: Configuracion ldap/ldap.conf LDAP
          copy: src=template/ldap/ldap.conf_cliente dest=/etc/ldap/ldap.conf
